#ifndef TRUNK_SOURCE_OPT_TOOLS_INCLUDE_FINAL_CODE_GEN_H_
#define TRUNK_SOURCE_OPT_TOOLS_INCLUDE_FINAL_CODE_GEN_H_

void ReplaceMemcpyByBruteForce(CSageCodeGen *codegen, void *expr);

#endif  // TRUNK_SOURCE_OPT_TOOLS_INCLUDE_FINAL_CODE_GEN_H_
